notes/urls.py
from django.urls import path

from .views import (
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    NoteListView,
    NoteCreateView,
    NoteUpdateView,
    NoteDeleteView,
    AuthorDetailView,
    archive_note,
    unarchive_note,
)

urlpatterns = [
    path(
        "category/",
        CategoryListView.as_view(),
        name="category-list",
    ),
    path(
        "category/create/",
        CategoryCreateView.as_view(),
        name="category-create",
    ),
    path(
        "category/<int:pk>/update/",
        CategoryUpdateView.as_view(),
        name="category-update",
    ),
    path(
        "category/<int:pk>/delete/",
        CategoryDeleteView.as_view(),
        name="category-delete",
    ),
    path("", NoteListView.as_view(), name="note-list"),
    path("note/create/", NoteCreateView.as_view(), name="note-create"),
    path(
        "note/<int:pk>/update/", NoteUpdateView.as_view(), name="note-update"
    ),
    path(
        "note/<int:pk>/delete/", NoteDeleteView.as_view(), name="note-delete"
    ),
    path("author/<int:pk>/", AuthorDetailView.as_view(), name="author-detail"),
    path("note/<int:pk>/archive/", archive_note, name="archive_note"),
    path("note/<int:pk>/unarchive/", unarchive_note, name="unarchive_note"),
]

app_name = "notes"

notes_application/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("notes.urls", namespace="notes")),
    path("accounts/", include("allauth.urls")),
]

config/models.py
from dataclasses import dataclass


@dataclass
class DatabaseConfig:
    user: str
    password: str
    host: str
    name: str


@dataclass
class SettingsConfig:
    secret_key: str
    debug: bool
    client_id: str
    secret: str
    email_host_user: str
    email_host_password: str


@dataclass
class Config:
    settings_config: SettingsConfig
    db_config: DatabaseConfig

notes/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser

import re


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    color = models.CharField(max_length=255)

    class Meta:
        ordering = ["-id"]
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return f"{self.name} {self.color}"


class Author(AbstractUser):

    class Meta:
        verbose_name = "author"
        verbose_name_plural = "authors"

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("notes:author-detail", kwargs={"pk": self.pk})


class Note(models.Model):
    text = models.TextField(blank=True, null=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="categories",
        blank=True,
        null=True,
    )
    author = models.ForeignKey(
        Author,
        related_name="authors",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    active = models.BooleanField(default=True)
    last_updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    total_words = models.IntegerField(blank=True, null=True)
    total_unique_words = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ["-last_updated"]

    def save(self, *args, **kwargs):

        self.find_all_words()
        super().save(*args, **kwargs)

    def find_all_words(self):

        words = re.findall(r"[a-zA-Z][a-zA-Z']*|[\d.]+", self.text)
        self.total_words = len(words)

        unique_words = set(words)
        self.total_unique_words = len(unique_words)

notes/forms.py
from django import forms

from notes.models import Category, Note


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = "__all__"
        widgets = {
            "color": forms.HiddenInput(attrs={"id": "id_color"}),
        }


class NoteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(NoteForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(NoteForm, self).save(commit=False)
        if self.request and self.request.user.is_authenticated:
            instance.author = self.request.user
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Note
        fields = ["category", "text", "active"]


class NoteFilterForm(forms.ModelForm):
    SORTED_CHOICES = [
        ("last_updated", "Data Update (Newest First)"),
        ("-last_updated", "Data Update (Oldest First)"),
        ("created", "Data Create (Newest First)"),
        ("-created", "Data Create (Oldest First)"),
        ("total_words", "Total Words"),
        ("unique_words", "Unique Words"),
    ]

    active = forms.BooleanField(label="Archived", required=False)
    sorted_by = forms.ChoiceField(
        label="Sorted", choices=SORTED_CHOICES, required=False
    )

    class Meta:
        model = Note
        fields = ["category", "active", "sorted_by"]

notes/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.http import JsonResponse

from notes.forms import CategoryForm, NoteForm, NoteFilterForm
from notes.models import Category, Note, Author


class CategoryListView(generic.ListView):
    model = Category
    context_object_name = "category_list"
    template_name = "notes/category_list.html"
    paginate_by = 7


class CategoryCreateView(generic.CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy("notes:note-create")


class CategoryUpdateView(generic.UpdateView):
    model = Category
    fields = "__all__"
    success_url = reverse_lazy("notes:category-list")


class CategoryDeleteView(generic.DeleteView):
    model = Category
    success_url = reverse_lazy("notes:category-list")


class NoteListView(generic.ListView):
    model = Note
    paginate_by = 7
    template_name = "notes/note_list.html"

    def get_queryset(self):
        queryset = super().get_queryset().select_related("category", "author")
        category = self.request.GET.get("category")
        active = self.request.GET.get("active")
        sorted_by = self.request.GET.get("sorted_by")

        if category:
            queryset = queryset.filter(category__id=category)

        if active == "on":
            queryset = queryset.filter(active=False)
        else:
            queryset = queryset.filter(active=True)

        if sorted_by:
            if sorted_by == "total_words":
                queryset = queryset.order_by("total_words")
            elif sorted_by == "unique_words":
                queryset = queryset.order_by("total_unique_words")
            else:
                queryset = queryset.order_by(sorted_by)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = NoteFilterForm(self.request.GET)
        return context


class NoteCreateView(generic.CreateView):
    model = Note
    form_class = NoteForm
    success_url = reverse_lazy("notes:note-list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class NoteUpdateView(generic.UpdateView):
    model = Note
    form_class = NoteForm
    success_url = reverse_lazy("notes:note-list")


class NoteDeleteView(generic.DeleteView):
    model = Note
    success_url = reverse_lazy("notes:note-list")


class AuthorDetailView(generic.DetailView):
    model = Author


def archive_note(request, pk):
    note = Note.objects.get(pk=pk)
    note.active = False
    note.save()
    return JsonResponse({"success": True})


def unarchive_note(request, pk):
    note = Note.objects.get(pk=pk)
    note.active = True
    note.save()
    return JsonResponse({"success": True})

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  {% block title %}<title>Notes Application</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" size="32" href="{% static 'images/fav-icon.png' %}" data-hid="63b4eb3">

  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
  <link rel="stylesheet" href="{% static 'css/pagination.css' %}">
  {% block head %}{% endblock %}
</head>

<body class="main-body">
  {% include "includes/navbar.html" %}

  <div class="container">
    <div class="main-content">
      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}
    </div>
  </div>
</body>

{% block bottom_block %}{% endblock %}

</html>

templates/includes/filter_form.html
<form method="get" class="note-filter-form" action="">
  <div class="form-row">
    <div class="form-field">
      <label class="wrap-category" for="id_category">Category:</label>
      {{ form.category }}
    </div>
    <div class="form-field">
      <label class="wrap-sorted_by" for="id_sorted_by">Sorted by:</label>
      {{ form.sorted_by }}
    </div>
    <div class="form-field form-field-center">
      <label class="wrap-active" for="id_active">Show archive:</label>
      {{ form.active }}
    </div>
    <div class="form-field form-field-center">
      <button class="form-submit" type="submit">Filter</button>
    </div>
  </div>
</form>

templates/includes/navbar.html
<div class="container-navbar">
  <ul class="list-group-navbar">
    <li><a href="{% url 'notes:note-list' %}" class="list-group-item-navbar">Notes</a></li>
    <li><a href="{% url 'notes:category-list' %}" class="list-group-item-navbar">Category</a></li>
  </ul>

  {% if user.is_authenticated %}
    <div class="user-links-navbar">
      <span class="user-link">{{ user.get_username }}</span>
      <a href="{% url 'account_logout' %}?next={{ request.path }}" class="list-group-item-navbar logout-link">Logout</a>
    </div>
  {% else %}
    <a href="{% url 'account_login' %}?next={{ request.path }}" class="list-group-item-navbar login-link">Login</a>
  {% endif %}
</div>

templates/includes/pagination.html
{% load templatetags %}

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/notes/category_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1 class="category-heading">Delete category {{ category.name }}?</h1>
  <div class="category-container">
    <form class="category-form form-delete" action="" method="post">
      {% csrf_token %}
      <a class="cancel" href="{% url 'notes:category-list' %}">Cancel</a>
      <input class="submit" type="submit" value="Yes" class="btn btn-danger">
    </form>
  </div>
{% endblock %}

templates/notes/category_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}

  <h1 class="category-heading">{{ object|yesno:"Update,Create" }} category</h1>

  <div class="category-container">

    {{ form.name.errors | safe }}
    <form class="category-form" action="" method="post" novalidate>
      {% csrf_token %}

      <div class="wrap-input">
        {{ form.name|attr:"class:input" }}
        <label for="id_name">Name</label>
      </div>

      {{ form.color|attr:"class:input-hidden" }}

      <input class="submit" type="submit" value="Submit" class="">
    </form>

    <div class="category-input">
      <input class="jscolor" value="Click to select a color" data-jscolor="{valueElement: '#id_color'}">
    </div>

  </div>

{% endblock %}


{% block bottom_block %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jscolor/2.4.6/jscolor.min.js"></script>
  {% load static %}
  <script src="{% static 'js/category/color.js' %}"></script>
{% endblock %}

templates/notes/category_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <h1 class="category-heading">
    Category List
    <a href="{% url 'notes:category-create' %}" style="margin-left: 2%;">
      <img src="{% static 'images/plus.svg' %}" alt="checkmark">
    </a>
  </h1>

  {% if category_list %}
    <div class="category-container">
      <ul class="category-list">
        {% for category in category_list %}
          <li class="category-item">
            <div class="category-item-container">
              <div class="category-item-container-span">
                <span class="category-color" style="background: {{ category.color }}"></span>
                <span class="category-name">{{ category.name }}</span>
              </div>
              <div>
                <a href="{% url 'notes:category-update' pk=category.id %}" class="update-link img-setting">
                  <img src="{% static "images/update.svg" %}" alt="Update"></a>
                <a href="{% url 'notes:category-delete' pk=category.id %}" class="delete-link img-setting">
                  <img src="{% static "images/delete.svg" %}" alt="Delete">
                </a>
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
  {% else %}
    <p class="no-categories">There are no categories in notes</p>
  {% endif %}
{% endblock %}

templates/notes/note_confirm_delete.html
{% extends "base.html" %}


{% block content %}
  <h1 class="category-heading">Delete note?</h1>
  <div class="category-container">
    <form class="category-form form-delete" action="" method="post">
      {% csrf_token %}
      <a class="cancel" href="{% url 'notes:note-list' %}">Cancel</a>
      <input class="submit" type="submit" value="Yes" class="btn btn-danger">
    </form>
  </div>
{% endblock %}

templates/notes/note_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}

  <h1 class="category-heading">{{ object|yesno:"Update,Create" }} note</h1>

  <div class="category-container">
    <form class="note-form" action="" method="post" novalidate>
      {% csrf_token %}


      <div class="wrap-group">

        <div class="wrap-select">
          <label class="wrap-category" for="id_category">Category:</label>
          {{ form.category|attr:"class:select" }}
          <span name="color" id="color" class="category-color" style="background: #ffffff"></span>
        </div>

        <div class="wrap-select">
          <label class="wrap-category" for="id_category">Create new category:</label>
          <a href="{% url 'notes:category-create' %}" style="margin-left: 2%;">
            <img src="{% static 'images/plus.svg' %}" alt="checkmark">
          </a>
        </div>

        <div class="wrap-checkbox">
          <label class="wrap-active" for="id_active">Active:</label>
          {{ form.active|attr:"class:checkbox" }}
        </div>
      </div>

      <div class="wrap-input-text">
        {{ form.text|attr:"class:input-text" }}
      </div>

      <div class="submit-center">
        <input class="submit" type="submit" value="Submit" class="">
      </div>
    </form>
  </div>

{% endblock %}

{% block bottom_block %}

  {% load static %}
  <script src="{% static 'js/note/color-from-select.js' %}"></script>
{% endblock %}

templates/notes/note_list.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/filter_form.css' %}">
{% endblock %}

{% block content %}
  <h1 class="category-heading">
    Note list
    <a href="{% url 'notes:note-create' %}" style="margin-left: 2%;">
      <img src="{% static 'images/plus.svg' %}" alt="checkmark">
    </a>
  </h1>

  <div class="category-heading form-container">
    {% include "includes/filter_form.html" %}
  </div>

  {% if note_list %}
    <div class="category-container">
      <ul class="category-list">
        {% for note in note_list %}
          <li class="category-item">
            <div class="category-item-container">
              <div class="category-item-container-span">
                <span class="category-color" style="background: {{ note.category.color }}"></span>
                <span class="category-name">
                  <a href="{% url "notes:note-update" pk=note.id %}" class="detail-note">
                    {{ note.text|truncatechars:50 }}
                    </a>
                </span>
              </div>
              <div class="note-end-block">
                <span class="note-author">
                  {% if note.author %}
                    {{ note.author }}<span class="last_updated"> {{ note.last_updated }}</span>
                  {% else %}
                    <span class="last_updated">{{ note.last_updated }}</span>
                  {% endif %}
                </span>
                {% if note.active %}
                  <button class="archive-button submit" data-note-id="{{ note.pk }}">Add to archive</button>
                {% else %}
                  <button class="unarchive-button submit" data-note-id="{{ note.pk }}">Unarchive</button>
                {% endif %}
                <div class="img-div">
                <a href="{% url "notes:note-update" pk=note.id %}" class="update-link img-setting">
                  <img src="{% static "images/update.svg" %}" alt="Update"></a>
                <a href="{% url "notes:note-delete" pk=note.id %}" class="delete-link img-setting">
                  <img src="{% static "images/delete.svg" %}" alt="Delete">
                </a>
                  </div>
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
  {% else %}
    <p class="no-categories">There are no notes.</p>
  {% endif %}
{% endblock %}


{% block bottom_block %}

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
      var csrfToken = '{{ csrf_token }}';
  </script>
  <script src="{% static 'js/note/arhivator.js' %}"></script>

{% endblock %}